# Generated by Django 4.2.8 on 2024-03-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drf_app.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('exp_date', models.DateField(default=drf_app.utils.define_exp_date, verbose_name='Дата истечения срока')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
